apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evidently.configSecretName" . }}
  namespace: {{ include "evidently.namespace" . }}
  labels:
    {{- include "evidently.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
type: Opaque
stringData:
  config.yaml: |
    storage:
      type: sql

    database:
      url: {{ include "evidently.databaseUrl" . }}

    dataset_storage:
      type: fsspec
      path: /app/workspace
