apiVersion: v1
kind: Service
metadata:
  name: {{ include "evidently.postgresHeadlessName" . }}
  namespace: {{ include "evidently.namespace" . }}
  labels:
    {{- include "evidently.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "evidently.postgresName" . }}
  namespace: {{ include "evidently.namespace" . }}
  labels:
    {{- include "evidently.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
